import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { importHarness } from '../src/importer.js';
import { compileToProgram } from '../src/compiler.js';

function tmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'graft-import-'));
}

function writeAgent(dir: string, name: string, content: string) {
  const agentsDir = path.join(dir, '.claude', 'agents');
  fs.mkdirSync(agentsDir, { recursive: true });
  fs.writeFileSync(path.join(agentsDir, `${name}.md`), content);
}

function writeHook(dir: string, filename: string, content: string) {
  const hooksDir = path.join(dir, '.claude', 'hooks');
  fs.mkdirSync(hooksDir, { recursive: true });
  fs.writeFileSync(path.join(hooksDir, filename), content);
}

function writeSettings(dir: string, settings: object) {
  const claudeDir = path.join(dir, '.claude');
  fs.mkdirSync(claudeDir, { recursive: true });
  fs.writeFileSync(path.join(claudeDir, 'settings.json'), JSON.stringify(settings));
}

function writeOrchestration(dir: string, content: string) {
  const claudeDir = path.join(dir, '.claude');
  fs.mkdirSync(claudeDir, { recursive: true });
  fs.writeFileSync(path.join(claudeDir, 'orchestration.md'), content);
}

const AGENT_TEMPLATE = (name: string, model: string, produces: string, fields: string, reads: string = 'Input') => `---
name: ${name.toLowerCase()}
description: ${name} agent — produces ${produces}
model: ${model}
---

# ${name} Agent

## Context Loading
- Load \`${reads}\` from \`.graft/session/\`
## Output Contract
Produce JSON output matching this schema:
\`\`\`json
{
${fields}
}
\`\`\`

## Token Discipline
- Input budget: 4,000 tokens. Read only what is necessary.
- Output budget: 2,000 tokens. No explanations, no reasoning traces.
- Output ONLY the JSON result.

## Completion Protocol
1. Write result to \`.graft/session/node_outputs/${name.toLowerCase()}.json\`
2. Output: \`===NODE_COMPLETE:${name.toLowerCase()}===\`
`;

const HOOK_TEMPLATE = (source: string, target: string, fields: string[]) => `#!/usr/bin/env node
// Auto-generated by Graft Compiler
// Edge: ${source} -> ${target}

const fs = require('fs');
const path = require('path');

const INPUT = path.resolve('.graft/session/node_outputs/${source.toLowerCase()}.json');
const OUTPUT = path.resolve('.graft/session/node_outputs/${source.toLowerCase()}_to_${target.toLowerCase()}.json');

const raw = fs.readFileSync(INPUT, 'utf-8');
const data = JSON.parse(raw);

function compact(data) {
  if (typeof data !== 'object') return data;
  const result = {};
  for (const [key, val] of Object.entries(data)) {
    if (val !== null && val !== undefined && val !== '') result[key] = val;
  }
  return result;
}

let result = {
${fields.map(f => `  "${f}": data["${f}"]`).join(',\n')}
};
result = compact(result);

fs.writeFileSync(OUTPUT, JSON.stringify(result));
`;

describe('graft import', () => {
  let dir: string;

  beforeEach(() => {
    dir = tmpDir();
  });

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  it('imports a single agent', () => {
    writeAgent(dir, 'analyzer', AGENT_TEMPLATE(
      'Analyzer', 'claude-sonnet-4-20250514', 'AnalysisResult',
      '  "issues": ["<string>"],\n  "score": 0'
    ));

    const gft = importHarness(dir);
    expect(gft).toContain('node Analyzer');
    expect(gft).toContain('model: sonnet');
    expect(gft).toContain('produces AnalysisResult');
    expect(gft).toContain('issues: List<String>');
    expect(gft).toContain('score: Int');
  });

  it('imports multiple agents with correct models', () => {
    writeAgent(dir, 'fast', AGENT_TEMPLATE(
      'Fast', 'claude-haiku-4-5-20251001', 'FastOutput',
      '  "result": "<string>"'
    ));
    writeAgent(dir, 'deep', AGENT_TEMPLATE(
      'Deep', 'claude-opus-4-20250514', 'DeepOutput',
      '  "analysis": "<string>"'
    ));

    const gft = importHarness(dir);
    expect(gft).toContain('node Fast(model: haiku');
    expect(gft).toContain('node Deep(model: opus');
  });

  it('imports hooks as edge declarations with transforms', () => {
    writeAgent(dir, 'source', AGENT_TEMPLATE('Source', 'claude-sonnet-4-20250514', 'SourceOut', '  "data": "<string>"'));
    writeAgent(dir, 'target', AGENT_TEMPLATE('Target', 'claude-sonnet-4-20250514', 'TargetOut', '  "result": "<string>"', 'SourceOut'));
    writeHook(dir, 'source-to-target.js', HOOK_TEMPLATE('Source', 'Target', ['data']));

    const gft = importHarness(dir);
    expect(gft).toContain('edge Source -> Target');
    expect(gft).toContain('select(data)');
    expect(gft).toContain('compact');
  });

  it('imports settings with model routing and budget', () => {
    writeAgent(dir, 'worker', AGENT_TEMPLATE('Worker', 'claude-sonnet-4-20250514', 'WorkerOut', '  "x": "<string>"'));
    writeSettings(dir, {
      graft: {
        budget: { total: 30000 },
        model_routing: {
          overrides: { worker: 'claude-opus-4-20250514' }
        }
      }
    });

    const gft = importHarness(dir);
    expect(gft).toContain('model: opus');
    expect(gft).toContain('budget: 30k');
  });

  it('imports orchestration flow with parallel steps', () => {
    writeAgent(dir, 'a', AGENT_TEMPLATE('A', 'claude-sonnet-4-20250514', 'AOut', '  "x": "<string>"'));
    writeAgent(dir, 'b', AGENT_TEMPLATE('B', 'claude-sonnet-4-20250514', 'BOut', '  "x": "<string>"'));
    writeAgent(dir, 'c', AGENT_TEMPLATE('C', 'claude-sonnet-4-20250514', 'COut', '  "x": "<string>"', 'AOut'));
    writeOrchestration(dir, `# Orchestration
### Step 1: [parallel] A, B
- Dispatch agents
### Step 2: C [sequential]
- Agent: c
`);

    const gft = importHarness(dir);
    expect(gft).toContain('parallel { A  B }');
    expect(gft).toContain('-> C -> done');
  });

  it('detects context types from reads', () => {
    writeAgent(dir, 'worker', AGENT_TEMPLATE('Worker', 'claude-sonnet-4-20250514', 'WorkerOut', '  "x": "<string>"'));

    const gft = importHarness(dir);
    expect(gft).toContain('context Input');
  });

  it('generates valid .gft that passes graft check', () => {
    writeAgent(dir, 'analyzer', AGENT_TEMPLATE(
      'Analyzer', 'claude-sonnet-4-20250514', 'Analysis',
      '  "findings": ["<string>"],\n  "severity": "<string>"'
    ));
    writeAgent(dir, 'reviewer', AGENT_TEMPLATE(
      'Reviewer', 'claude-sonnet-4-20250514', 'Review',
      '  "approved": true,\n  "comments": "<string>"',
      'Analysis'
    ));
    writeHook(dir, 'analyzer-to-reviewer.js', HOOK_TEMPLATE('Analyzer', 'Reviewer', ['findings', 'severity']));
    writeSettings(dir, { graft: { budget: { total: 20000 } } });
    writeOrchestration(dir, `# Orch
### Step 1: Analyzer [sequential]
- Agent: analyzer
### Step 2: Reviewer [sequential]
- Agent: reviewer
`);

    const gft = importHarness(dir);

    // Should produce valid .gft
    // Add context fields to make it compilable
    const withFields = gft.replace('// TODO: add fields', 'question: String');
    const result = compileToProgram(withFields, 'imported.gft');
    expect(result.success).toBe(true);
    expect(result.program!.nodes).toHaveLength(2);
    expect(result.program!.edges).toHaveLength(1);
  });

  it('imports from benchmark output and round-trips', () => {
    // Use the actual benchmark output
    const benchDir = path.resolve('benchmarks/output/code-review');
    if (!fs.existsSync(benchDir)) return; // skip if benchmarks not present

    const gft = importHarness(benchDir);

    // Should have 4 nodes
    expect(gft).toContain('node SecurityReviewer');
    expect(gft).toContain('node LogicReviewer');
    expect(gft).toContain('node PerformanceReviewer');
    expect(gft).toContain('node SeniorReviewer');

    // Should have 3 edges
    expect(gft).toContain('edge SecurityReviewer -> SeniorReviewer');
    expect(gft).toContain('edge LogicReviewer -> SeniorReviewer');
    expect(gft).toContain('edge PerformanceReviewer -> SeniorReviewer');

    // Should have parallel flow
    expect(gft).toContain('parallel {');

    // Should compile without errors (context has TODO, so skip full compile)
    const withFields = gft.replace('// TODO: add fields', 'diff: String\n  description: String\n  files_changed: List<String>');
    const result = compileToProgram(withFields, 'imported.gft');
    expect(result.success).toBe(true);
  });

  it('handles empty hooks directory', () => {
    writeAgent(dir, 'solo', AGENT_TEMPLATE('Solo', 'claude-sonnet-4-20250514', 'SoloOut', '  "result": "<string>"'));

    const gft = importHarness(dir);
    expect(gft).toContain('node Solo');
    expect(gft).not.toContain('edge');
  });

  it('extracts budget from agent definition', () => {
    const customAgent = AGENT_TEMPLATE('Big', 'claude-opus-4-20250514', 'BigOut', '  "x": "<string>"')
      .replace('Input budget: 4,000 tokens', 'Input budget: 12,000 tokens')
      .replace('Output budget: 2,000 tokens', 'Output budget: 6,000 tokens');
    writeAgent(dir, 'big', customAgent);

    const gft = importHarness(dir);
    expect(gft).toContain('budget: 12k/6k');
  });
});
