import { NodeDecl, EdgeDecl } from '../parser/ast.js';
import { CodegenBackend, CodegenContext } from './backend.js';
import { fieldsToJsonExample } from '../utils.js';
import { MODEL_MAP } from '../constants.js';
import { VERSION } from '../version.js';

/**
 * GenericBackend — a tool-agnostic codegen backend.
 *
 * Produces markdown agent files, JS hook stubs, and JSON settings
 * that are not tied to any specific AI coding assistant.
 * This is groundwork for future Cursor / Windsurf / Copilot support.
 */
export class GenericBackend implements CodegenBackend {
  readonly name = 'generic';

  generateAgent(node: NodeDecl, memoryNames: Set<string>, ctx: CodegenContext): string {
    const name = node.name.toLowerCase();
    const resolvedModel = MODEL_MAP[node.model] || node.model;
    const jsonSchema = fieldsToJsonExample(node.produces.fields);

    const readsList = node.reads
      .map(r => `- ${r.context}${r.field && r.field.length > 0 ? ` (fields: ${r.field.join(', ')})` : ''}`)
      .join('\n');

    const toolsList = node.tools.length > 0
      ? `\n## Tools\n${node.tools.map(t => `- ${t}`).join('\n')}\n`
      : '';

    return `# ${node.name} Agent

## Metadata
- **name**: ${name}
- **model**: ${resolvedModel}
- **produces**: ${node.produces.name}

## Reads
${readsList || '(none)'}
${toolsList}
## Output Schema
\`\`\`json
${JSON.stringify(jsonSchema, null, 2)}
\`\`\`

## Instructions
Execute the ${node.name} step of the pipeline.
Read the specified inputs, perform your task, and produce output matching the schema above.
Write your output as JSON to: .graft/session/node_outputs/${name}.json
`;
  }

  generateHook(edge: EdgeDecl, _ctx: CodegenContext): string | null {
    if (edge.transforms.length === 0) return null;
    if (edge.target.kind !== 'direct') return null;

    const source = edge.source.toLowerCase();
    const target = edge.target.node.toLowerCase();
    const transformNames = edge.transforms.map(t => t.type).join(', ');

    return `// Hook: ${edge.source} -> ${edge.target.node}
// Transforms: ${transformNames}
// Generated by Graft (generic backend)

import * as fs from 'node:fs';

const inputPath = '.graft/session/node_outputs/${source}.json';
const outputPath = '.graft/session/node_outputs/${source}_to_${target}.json';

const raw = JSON.parse(fs.readFileSync(inputPath, 'utf-8'));

// TODO: Implement transforms: ${transformNames}
const result = raw;

fs.writeFileSync(outputPath, JSON.stringify(result, null, 2));
`;
  }

  generateConditionalHook(edge: EdgeDecl, _ctx: CodegenContext): string | null {
    if (edge.target.kind !== 'conditional') return null;

    const source = edge.source.toLowerCase();
    const branches = edge.target.branches;

    const branchLines = branches.map(b => {
      const condition = b.condition ? `/* condition */` : `/* else */`;
      return `  ${condition} '${b.target}'`;
    }).join(',\n');

    return `// Router: ${edge.source} -> conditional
// Generated by Graft (generic backend)

import * as fs from 'node:fs';

const inputPath = '.graft/session/node_outputs/${source}.json';
const routingPath = '.graft/session/routing/${source}_route.json';

const data = JSON.parse(fs.readFileSync(inputPath, 'utf-8'));

// TODO: Implement conditional routing logic
const routes = [
${branchLines}
];

const selectedRoute = routes[routes.length - 1]; // default: last (else) branch
fs.writeFileSync(routingPath, JSON.stringify({ route: selectedRoute }, null, 2));
`;
  }

  generateOrchestration(ctx: CodegenContext): string {
    const graph = ctx.program.graphs[0];
    const graphName = graph?.name ?? 'pipeline';
    const nodes = ctx.program.nodes.map(n => n.name);

    const flowSteps = graph?.flow.map(step => {
      if (step.kind === 'node') return `1. Run **${step.name}**`;
      if (step.kind === 'parallel') return `1. Run in parallel: ${step.branches.join(', ')}`;
      return '';
    }).filter(Boolean).join('\n') ?? '';

    return `# ${graphName} — Orchestration

> Generated by Graft v${VERSION} (generic backend)
> Source: ${ctx.sourceFile}

## Pipeline Flow
${flowSteps}

## Nodes
${nodes.map(n => `- ${n}`).join('\n')}

## Runtime
This pipeline was compiled with the generic backend.
To execute, run each node in order according to the flow above,
passing outputs between nodes via .graft/session/node_outputs/.
`;
  }

  generateSettings(ctx: CodegenContext): Record<string, unknown> {
    const graph = ctx.program.graphs[0];
    const firstNode = ctx.program.nodes[0];
    const defaultModel = firstNode
      ? (MODEL_MAP[firstNode.model] || firstNode.model)
      : 'default';

    const overrides: Record<string, string> = {};
    for (const node of ctx.program.nodes) {
      overrides[node.name] = MODEL_MAP[node.model] || node.model;
    }

    return {
      graft: {
        version: VERSION,
        backend: 'generic',
        source: ctx.sourceFile,
        compiled_at: new Date().toISOString(),
        budget: {
          total: graph?.budget ?? 0,
        },
        model_routing: {
          default: defaultModel,
          overrides,
        },
        nodes: ctx.program.nodes.map(n => n.name),
        edges: ctx.program.edges.map(e => ({
          source: e.source,
          target: e.target.kind === 'direct' ? e.target.node : 'conditional',
        })),
      },
    };
  }
}
