import { EdgeDecl, Transform } from '../parser/ast.js';

// Note: Generated scripts require bash (Git Bash on Windows).
// If hook execution fails on Windows, prefix commands with `bash` in settings.ts.

export function generateHook(edge: EdgeDecl): string | null {
  if (edge.transforms.length === 0) return null;
  if (edge.target.kind !== 'direct') return null;

  const source = edge.source.toLowerCase();
  const target = edge.target.node.toLowerCase();
  const jqExpr = transformsToJq(edge.transforms);

  return `#!/bin/bash
# Auto-generated by Graft Compiler
# Edge: ${edge.source} -> ${edge.target.node}
set -euo pipefail

INPUT=".graft/session/node_outputs/${source}.json"
OUTPUT=".graft/session/node_outputs/${source}_to_${target}.json"
TOKEN_LOG=".graft/token_log.txt"

if [ ! -f "$INPUT" ]; then
  echo "[Graft] ERROR: ${edge.source} output not found at $INPUT" >&2
  exit 1
fi

jq ${jqExpr} "$INPUT" > "$OUTPUT"

# Token accounting
ORIGINAL=$(wc -c < "$INPUT")
TRANSFORMED=$(wc -c < "$OUTPUT")
if [ "$ORIGINAL" -gt 0 ]; then
  REDUCTION=$(( (ORIGINAL - TRANSFORMED) * 100 / ORIGINAL ))
else
  REDUCTION=0
fi
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

echo "[$TIMESTAMP] Edge ${edge.source}->${edge.target.node} | \${ORIGINAL}B -> \${TRANSFORMED}B (\${REDUCTION}% reduction)" >> "$TOKEN_LOG"
`;
}

function transformsToJq(transforms: Transform[]): string {
  const selectFields: string[] = [];
  const dropFields: string[] = [];
  const filterExprs: string[] = [];
  let isCompact = false;

  for (const t of transforms) {
    switch (t.type) {
      case 'select':
        selectFields.push(...t.fields);
        break;
      case 'drop':
        dropFields.push(t.field);
        break;
      case 'filter':
        filterExprs.push(filterToJq(t));
        break;
      case 'compact':
        isCompact = true;
        break;
      case 'truncate':
        // Best-effort: truncate handled at string level
        break;
    }
  }

  const parts: string[] = [];

  if (selectFields.length > 0) {
    const fields = selectFields.map(f => `${f}: .${f}`).join(', ');
    parts.push(`{${fields}}`);
  }

  for (const f of dropFields) {
    parts.push(`del(.${f})`);
  }

  for (const expr of filterExprs) {
    parts.push(expr);
  }

  let expression = parts.length > 0 ? `'${parts.join(' | ')}'` : "'.'";

  if (isCompact) {
    expression = `-c ${expression}`;
  }

  return expression;
}

function filterToJq(t: Extract<Transform, { type: 'filter' }>): string {
  const { field, condition } = t;
  const valueStr = typeof condition.value === 'string'
    ? `"${condition.value}"`
    : String(condition.value);
  return `{${field}: [.${field}[] | select(.${condition.field} ${condition.op} ${valueStr})]}`;
}
