import { EdgeDecl, Transform } from '../parser/ast.js';
import { formatExpr } from '../format.js';

export function generateHook(edge: EdgeDecl): string | null {
  if (edge.transforms.length === 0) return null;
  if (edge.target.kind !== 'direct') return null;

  const source = edge.source.toLowerCase();
  const target = edge.target.node.toLowerCase();
  const transformCode = transformsToJs(edge.transforms);

  return `#!/usr/bin/env node
// Auto-generated by Graft Compiler
// Edge: ${edge.source} -> ${edge.target.node}

const fs = require('fs');
const path = require('path');

const INPUT = path.resolve('.graft/session/node_outputs/${source}.json');
const OUTPUT = path.resolve('.graft/session/node_outputs/${source}_to_${target}.json');
const TOKEN_LOG = path.resolve('.graft/token_log.txt');

if (!fs.existsSync(INPUT)) {
  console.error('[Graft] ERROR: ${edge.source} output not found at ' + INPUT);
  process.exit(1);
}

const raw = fs.readFileSync(INPUT, 'utf-8');
const data = JSON.parse(raw);

${transformCode}

const output = JSON.stringify(result);
fs.writeFileSync(OUTPUT, output);

// Token accounting
const original = Buffer.byteLength(raw);
const transformed = Buffer.byteLength(output);
const reduction = original > 0 ? Math.round((original - transformed) * 100 / original) : 0;
const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19);

fs.appendFileSync(TOKEN_LOG, \`[\${timestamp}] Edge ${edge.source}->${edge.target.node} | \${original}B -> \${transformed}B (\${reduction}% reduction)\\n\`);
`;
}

function transformsToJs(transforms: Transform[]): string {
  const selectFields: string[] = [];
  const dropFields: string[] = [];
  const filterExprs: string[] = [];
  let isCompact = false;

  for (const t of transforms) {
    switch (t.type) {
      case 'select':
        selectFields.push(...t.fields);
        break;
      case 'drop':
        dropFields.push(t.field);
        break;
      case 'filter':
        filterExprs.push(filterToJs(t));
        break;
      case 'compact':
        isCompact = true;
        break;
      case 'truncate':
        break;
    }
  }

  const lines: string[] = [];

  if (selectFields.length > 0) {
    const picks = selectFields.map(f => `  ${JSON.stringify(f)}: data[${JSON.stringify(f)}]`).join(',\n');
    lines.push(`let result = {\n${picks}\n};`);
  } else {
    lines.push('let result = { ...data };');
  }

  for (const f of dropFields) {
    lines.push(`delete result[${JSON.stringify(f)}];`);
  }

  for (const expr of filterExprs) {
    lines.push(expr);
  }

  // compact is implicit — JSON.stringify without spacing
  // (non-compact would use JSON.stringify(result, null, 2))
  if (!isCompact) {
    lines.push('// Note: non-compact output');
    lines.push('result = JSON.parse(JSON.stringify(result));');
  }

  return lines.join('\n');
}

function filterToJs(t: Extract<Transform, { type: 'filter' }>): string {
  const { field, condition } = t;
  if (condition.kind !== 'binary') return `result[${JSON.stringify(field)}] = result[${JSON.stringify(field)}];`;
  const fieldName = condition.left.kind === 'field_access'
    ? condition.left.segments[condition.left.segments.length - 1]
    : formatExpr(condition.left);
  const valueStr = condition.right.kind === 'literal'
    ? JSON.stringify(condition.right.value)
    : formatExpr(condition.right);
  const op = condition.op === '==' ? '===' : condition.op === '!=' ? '!==' : condition.op;
  return `result[${JSON.stringify(field)}] = (result[${JSON.stringify(field)}] || []).filter(item => item[${JSON.stringify(fieldName)}] ${op} ${valueStr});`;
}
