import { EdgeDecl, Transform } from '../parser/ast.js';
import { formatExpr } from '../format.js';

export function generateHook(edge: EdgeDecl): string | null {
  if (edge.transforms.length === 0) return null;
  if (edge.target.kind !== 'direct') return null;

  const source = edge.source.toLowerCase();
  const target = edge.target.node.toLowerCase();
  const { code: transformCode, isCompact, needsCompactFn, needsTruncateFn } = transformsToJs(edge.transforms);
  const stringify = isCompact ? 'JSON.stringify(result)' : 'JSON.stringify(result, null, 2)';

  // Build helper functions section
  const helpers: string[] = [];
  if (needsCompactFn) {
    helpers.push(COMPACT_FN);
  }
  if (needsTruncateFn) {
    helpers.push(TRUNCATE_FN);
  }
  const helperSection = helpers.length > 0 ? '\n' + helpers.join('\n') + '\n' : '';

  return `#!/usr/bin/env node
// Auto-generated by Graft Compiler
// Edge: ${edge.source} -> ${edge.target.node}

const fs = require('fs');
const path = require('path');

const INPUT = path.resolve('.graft/session/node_outputs/${source}.json');
const OUTPUT = path.resolve('.graft/session/node_outputs/${source}_to_${target}.json');
const TOKEN_LOG = path.resolve('.graft/token_log.txt');

if (!fs.existsSync(INPUT)) {
  // Graceful no-op: this hook fires on ALL Write calls,
  // so the source output may not exist yet (different agent writing).
  process.exit(0);
}

const raw = fs.readFileSync(INPUT, 'utf-8');
const data = JSON.parse(raw);
${helperSection}
${transformCode}

const output = ${stringify};
fs.writeFileSync(OUTPUT, output);

// Token accounting
const original = Buffer.byteLength(raw);
const transformed = Buffer.byteLength(output);
const reduction = original > 0 ? Math.round((original - transformed) * 100 / original) : 0;
const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19);

fs.appendFileSync(TOKEN_LOG, \`[\${timestamp}] Edge ${edge.source}->${edge.target.node} | \${original}B -> \${transformed}B (\${reduction}% reduction)\\n\`);
`;
}

// Compact: recursively remove null, undefined, empty strings, empty arrays, empty objects
const COMPACT_FN = `function isEmpty(v) {
  if (v === null || v === undefined || v === '') return true;
  if (Array.isArray(v) && v.length === 0) return true;
  if (typeof v === 'object' && !Array.isArray(v) && Object.keys(v).length === 0) return true;
  return false;
}
function compact(data) {
  if (data === null || data === undefined) return undefined;
  if (typeof data !== 'object') return data;
  if (Array.isArray(data)) {
    return data.map(item => compact(item)).filter(item => !isEmpty(item));
  }
  const result = {};
  for (const [key, val] of Object.entries(data)) {
    const c = compact(val);
    if (!isEmpty(c)) result[key] = c;
  }
  return result;
}`;

// Truncate: proportionally reduce content to fit within token budget
const TRUNCATE_FN = `function truncate(data, maxTokens) {
  const maxChars = maxTokens * 4;
  const json = JSON.stringify(data);
  if (json.length <= maxChars) return data;
  if (typeof data === 'string') return data.slice(0, maxChars) + '...';
  if (typeof data !== 'object' || data === null) return data;
  const ratio = maxChars / json.length;
  return truncateDeep(data, ratio);
}
function truncateDeep(data, ratio) {
  if (data === null || data === undefined) return data;
  if (typeof data === 'string') {
    const maxLen = Math.max(10, Math.floor(data.length * ratio));
    return data.length > maxLen ? data.slice(0, maxLen) + '...' : data;
  }
  if (Array.isArray(data)) {
    const maxItems = Math.max(1, Math.floor(data.length * ratio));
    return data.slice(0, maxItems).map(item => truncateDeep(item, ratio));
  }
  if (typeof data === 'object') {
    const result = {};
    for (const [key, val] of Object.entries(data)) result[key] = truncateDeep(val, ratio);
    return result;
  }
  return data;
}`;

interface TransformResult {
  code: string;
  isCompact: boolean;
  needsCompactFn: boolean;
  needsTruncateFn: boolean;
}

function transformsToJs(transforms: Transform[]): TransformResult {
  const selectFields: string[] = [];
  const dropFields: string[] = [];
  const filterExprs: string[] = [];
  let isCompact = false;
  let truncateTokens: number | null = null;

  for (const t of transforms) {
    switch (t.type) {
      case 'select':
        selectFields.push(...t.fields);
        break;
      case 'drop':
        dropFields.push(t.field);
        break;
      case 'filter':
        filterExprs.push(filterToJs(t));
        break;
      case 'compact':
        isCompact = true;
        break;
      case 'truncate':
        truncateTokens = t.tokens;
        break;
    }
  }

  const lines: string[] = [];

  if (selectFields.length > 0) {
    const picks = selectFields.map(f => `  ${JSON.stringify(f)}: data[${JSON.stringify(f)}]`).join(',\n');
    lines.push(`let result = {\n${picks}\n};`);
  } else {
    lines.push('let result = { ...data };');
  }

  for (const f of dropFields) {
    lines.push(`delete result[${JSON.stringify(f)}];`);
  }

  for (const expr of filterExprs) {
    lines.push(expr);
  }

  if (isCompact) {
    lines.push('result = compact(result);');
  }

  if (truncateTokens !== null) {
    lines.push(`result = truncate(result, ${truncateTokens});`);
  }

  return {
    code: lines.join('\n'),
    isCompact,
    needsCompactFn: isCompact,
    needsTruncateFn: truncateTokens !== null,
  };
}

function filterToJs(t: Extract<Transform, { type: 'filter' }>): string {
  const { field, condition } = t;
  if (condition.kind !== 'binary') return `result[${JSON.stringify(field)}] = result[${JSON.stringify(field)}];`;
  const fieldName = condition.left.kind === 'field_access'
    ? condition.left.segments[condition.left.segments.length - 1]
    : formatExpr(condition.left);
  const valueStr = condition.right.kind === 'literal'
    ? JSON.stringify(condition.right.value)
    : formatExpr(condition.right);
  const op = condition.op === '==' ? '===' : condition.op === '!=' ? '!==' : condition.op;
  return `result[${JSON.stringify(field)}] = (result[${JSON.stringify(field)}] || []).filter(item => item[${JSON.stringify(fieldName)}] ${op} ${valueStr});`;
}
