import { Program, FlowNode, NodeDecl, EdgeDecl, Transform } from '../parser/ast.js';
import { TokenReport, NodeTokenReport } from '../analyzer/estimator.js';
import { ProgramIndex } from '../program-index.js';
import { formatExpr } from '../format.js';

interface EdgeInfo {
  transforms: Transform[];
}

export function generateOrchestration(program: Program, report: TokenReport): string {
  const graph = program.graphs[0];
  if (!graph) return '';

  const index = new ProgramIndex(program);
  const memoryNames = new Set(program.memories.map(m => m.name));

  const edgeMap = new Map<string, EdgeInfo>();
  const conditionalEdgeMap = new Map<string, EdgeDecl>();
  for (const edge of program.edges) {
    if (edge.target.kind === 'direct' && edge.transforms.length > 0) {
      edgeMap.set(`${edge.source}->${edge.target.node}`, { transforms: edge.transforms });
    } else if (edge.target.kind === 'conditional') {
      conditionalEdgeMap.set(edge.source, edge);
    }
  }

  const { text: steps } = generateSteps(graph.flow, report, edgeMap, conditionalEdgeMap, 1, null, index.nodeMap, memoryNames);

  // Memory preamble
  const memorySection = program.memories.length > 0
    ? `
## Persistent Memory
${program.memories.map(m => `- \`${m.name}\`: \`.graft/memory/${m.name.toLowerCase()}.json\` (${m.maxTokens.toLocaleString('en-US')} tokens max)`).join('\n')}
- Memories persist across runs. Nodes with \`writes\` clauses update memory after execution.

`
    : '';

  const paramsSection = graph.params.length > 0
    ? `\n## Parameters\n${graph.params.map(p => `- ${p.name}: ${p.type}${p.default !== undefined ? ` (default: ${p.default})` : ''}`).join('\n')}\n`
    : '';

  return `# Graft Orchestration: ${graph.name}

> Auto-generated by Graft Compiler. Edit the .gft source, not this file.
${paramsSection}
## Budget
Total: ${graph.budget.toLocaleString('en-US')} tokens
Best case: ${report.bestCase.toLocaleString('en-US')} tokens
Worst case: ${report.worstCase.toLocaleString('en-US')} tokens
${memorySection}
## Execution Plan
${steps}
## Token Budget Tracking
Check \`.graft/token_log.txt\` after each step.
- 80% consumed: switch remaining agents to compact mode
- 90% consumed: skip non-critical agents

## Failure Recovery
- Agent failure: follow on_failure policy in each agent definition
- Token overrun: switch to compact mode, then skip non-critical steps
- Complete failure: intermediate results preserved in \`.graft/session/\`
`;
}

function describeTransforms(transforms: Transform[]): string {
  const parts: string[] = [];
  for (const t of transforms) {
    switch (t.type) {
      case 'select':
        parts.push(`keep only fields: ${t.fields.map(f => `\`${f}\``).join(', ')}`);
        break;
      case 'drop':
        parts.push(`remove field \`${t.field}\``);
        break;
      case 'compact':
        parts.push('minify JSON (no whitespace)');
        break;
      case 'filter':
        parts.push(`filter \`${t.field}\` array`);
        break;
      case 'truncate':
        parts.push(`truncate to ${t.tokens} tokens`);
        break;
    }
  }
  return parts.join(', then ');
}

function describeCondition(expr: import('../parser/ast.js').Expr): string {
  if (expr.kind === 'binary') {
    const left = expr.left.kind === 'field_access' ? `\`${expr.left.segments[0]}\`` : formatExpr(expr.left);
    const right = expr.right.kind === 'literal' ? `\`${expr.right.value}\`` : formatExpr(expr.right);
    return `${left} ${expr.op} ${right}`;
  }
  return formatExpr(expr);
}

function generateConditionalRoutingStep(
  stepNum: number,
  edge: EdgeDecl,
  nodeMap: Map<string, NodeDecl>,
  report: TokenReport,
): string {
  if (edge.target.kind !== 'conditional') return '';

  const source = edge.source.toLowerCase();
  const branches = edge.target.branches;

  let text = `
### Step ${stepNum}: Conditional routing from ${edge.source}
- **Automatic**: Router hook evaluates conditions on ${edge.source}'s output
- Routing file: \`.graft/session/routing/${source}_route.json\`
- Read the \`target\` field and proceed accordingly:
`;

  for (const branch of branches) {
    const label = branch.condition ? describeCondition(branch.condition) : 'else (default)';
    if (branch.target === 'done') {
      text += `  - If ${label}: **pipeline complete**\n`;
    } else {
      const nodeReport = report.nodes.find(n => n.name === branch.target);
      const tokenInfo = nodeReport
        ? ` (tokens: input ~${nodeReport.estimatedIn.toLocaleString('en-US')} / output ~${nodeReport.estimatedOut.toLocaleString('en-US')})`
        : '';
      text += `  - If ${label}: run **${branch.target}** agent${tokenInfo}\n`;
    }
  }

  text += `- Each branch agent reads from \`.graft/session/node_outputs/${source}.json\`\n`;

  return text;
}

function generateSteps(
  flow: FlowNode[],
  report: TokenReport,
  edgeMap: Map<string, EdgeInfo>,
  conditionalEdgeMap: Map<string, EdgeDecl>,
  startStep: number,
  prevNode: string | null,
  nodeMap: Map<string, NodeDecl>,
  memoryNames: Set<string>,
): { text: string; nextStep: number; lastNode: string | null } {
  let text = '';
  let stepNum = startStep;
  let prev = prevNode;
  let prevParallelBranches: string[] = [];

  for (const step of flow) {
    switch (step.kind) {
      case 'node': {
        const lowerName = step.name.toLowerCase();
        const nodeReport = report.nodes.find(n => n.name === step.name);

        let inputSource = '';
        let transformNote = '';
        if (prev) {
          // Single predecessor (sequential)
          const edgeInfo = edgeMap.get(`${prev}->${step.name}`);
          if (edgeInfo) {
            inputSource = `\n- Input: \`.graft/session/node_outputs/${prev.toLowerCase()}_to_${lowerName}.json\``;
            transformNote = `\n- **Edge transform**: After ${prev} completes, transform its output: ${describeTransforms(edgeInfo.transforms)}. Save to \`.graft/session/node_outputs/${prev.toLowerCase()}_to_${lowerName}.json\` before starting ${step.name}.`;
          } else {
            inputSource = `\n- Input: \`.graft/session/node_outputs/${prev.toLowerCase()}.json\``;
          }
        } else if (prevParallelBranches.length > 0) {
          // Multiple predecessors (after parallel block)
          const inputs: string[] = [];
          const transforms: string[] = [];
          for (const branch of prevParallelBranches) {
            const edgeInfo = edgeMap.get(`${branch}->${step.name}`);
            if (edgeInfo) {
              const transformedPath = `.graft/session/node_outputs/${branch.toLowerCase()}_to_${lowerName}.json`;
              inputs.push(`\`${transformedPath}\``);
              transforms.push(`- **Edge transform** (${branch} → ${step.name}): ${describeTransforms(edgeInfo.transforms)}. Run: \`node .claude/hooks/${branch.toLowerCase()}-to-${lowerName}.js\` or manually apply. Output: \`${transformedPath}\``);
            } else {
              inputs.push(`\`.graft/session/node_outputs/${branch.toLowerCase()}.json\``);
            }
          }
          inputSource = `\n- Inputs: ${inputs.join(', ')}`;
          if (transforms.length > 0) {
            transformNote = '\n' + transforms.join('\n');
          }
        }

        let memoryLines = '';
        let additionalInputs = '';
        const nodeDecl = nodeMap.get(step.name);
        if (nodeDecl) {
          const memReads = nodeDecl.reads.filter(r => memoryNames.has(r.context));
          for (const mr of memReads) {
            memoryLines += `\n- Memory load: \`.graft/memory/${mr.context.toLowerCase()}.json\``;
          }
          for (const w of nodeDecl.writes) {
            if (memoryNames.has(w.memory)) {
              memoryLines += `\n- Memory save: \`.graft/memory/${w.memory.toLowerCase()}.json\``;
            }
          }
          // List produces-type reads that aren't covered by edges
          for (const ref of nodeDecl.reads) {
            if (memoryNames.has(ref.context)) continue; // already handled as memory
            // Find the node that produces this type
            const producerNode = [...nodeMap.values()].find(n => n.produces.name === ref.context);
            if (!producerNode || producerNode.name === step.name) continue;
            // Skip if already covered by edge-based input/transform
            const edgeKey = `${producerNode.name}->${step.name}`;
            if (edgeMap.has(edgeKey)) continue;
            // Skip if already in prevParallelBranches list (these are covered by the parallel input resolution above)
            if (prevParallelBranches.includes(producerNode.name)) continue;
            // Skip if this is the immediate sequential predecessor (already covered)
            if (prev === producerNode.name) continue;
            additionalInputs += `\n- Also reads: \`.graft/session/node_outputs/${producerNode.name.toLowerCase()}.json\` (${ref.context})`;
          }
        }

        text += `
### Step ${stepNum}: ${step.name} [sequential]
- Agent: ${lowerName}${inputSource}${transformNote}${additionalInputs}${memoryLines}
- Expected tokens: input ~${nodeReport?.estimatedIn.toLocaleString('en-US') || '?'} / output ~${nodeReport?.estimatedOut.toLocaleString('en-US') || '?'}
- Completion: \`===NODE_COMPLETE:${lowerName}===\`
- Output: \`.graft/session/node_outputs/${lowerName}.json\`
`;
        stepNum++;

        // Conditional routing after this node
        const condEdge = conditionalEdgeMap.get(step.name);
        if (condEdge && condEdge.target.kind === 'conditional') {
          text += generateConditionalRoutingStep(stepNum, condEdge, nodeMap, report);
          stepNum++;
        }

        prev = step.name;
        prevParallelBranches = [];
        break;
      }

      case 'parallel': {
        const branchList = step.branches.join(', ');
        text += `
### Step ${stepNum}: [parallel] ${branchList}
- **Dispatch all ${step.branches.length} agents concurrently** using the Agent tool in a single message
- Wait for all to complete before proceeding
`;
        // Collect edge transforms from preceding sequential node into parallel branches
        const incomingTransforms: string[] = [];
        for (const branchName of step.branches) {
          const lowerName = branchName.toLowerCase();
          const nodeReport = report.nodes.find(n => n.name === branchName);
          let branchInputNote = '';
          if (prev) {
            const edgeInfo = edgeMap.get(`${prev}->${branchName}`);
            if (edgeInfo) {
              const transformedPath = `.graft/session/node_outputs/${prev.toLowerCase()}_to_${lowerName}.json`;
              branchInputNote = ` [input: \`${transformedPath}\`]`;
              incomingTransforms.push(`- **Edge transform** (${prev} → ${branchName}): ${describeTransforms(edgeInfo.transforms)}. Run: \`node .claude/hooks/${prev.toLowerCase()}-to-${lowerName}.js\` or manually apply. Output: \`${transformedPath}\``);
            } else {
              branchInputNote = ` [input: \`.graft/session/node_outputs/${prev.toLowerCase()}.json\`]`;
            }
          }
          let branchMemAnnotations = '';
          const branchDecl = nodeMap.get(branchName);
          if (branchDecl) {
            const memReads = branchDecl.reads.filter(r => memoryNames.has(r.context));
            for (const mr of memReads) {
              branchMemAnnotations += ` [mem-read: ${mr.context.toLowerCase()}]`;
            }
            for (const w of branchDecl.writes) {
              if (memoryNames.has(w.memory)) {
                branchMemAnnotations += ` [mem-write: ${w.memory.toLowerCase()}]`;
              }
            }
          }
          text += `- Agent: ${lowerName} -- tokens: input ~${nodeReport?.estimatedIn.toLocaleString('en-US') || '?'} / output ~${nodeReport?.estimatedOut.toLocaleString('en-US') || '?'}${branchInputNote}${branchMemAnnotations}
`;
        }
        if (incomingTransforms.length > 0) {
          text += incomingTransforms.join('\n') + '\n';
        }
        text += `- Completion: all ${step.branches.length} \`===NODE_COMPLETE===\` signals received
`;
        // Track parallel branches for downstream edge resolution
        prevParallelBranches = [...step.branches];
        prev = null;
        stepNum++;
        break;
      }

      case 'foreach': {
        text += `
### Step ${stepNum}: [foreach over ${step.source}.output.${step.field}, max ${step.maxIterations} iterations]
- For each \`${step.binding}\` in list:
`;
        let subLetter = 'a';
        for (const bodyStep of step.body) {
          if (bodyStep.kind === 'node') {
            text += `  - Sub-step ${stepNum}${subLetter}: ${bodyStep.name} [foreach-body]
`;
            subLetter = String.fromCharCode(subLetter.charCodeAt(0) + 1);
          }
        }
        text += `- Completion: all iterations done or list exhausted
`;
        prev = null;
        stepNum++;
        break;
      }

      case 'let':
        text += `
### Step ${stepNum}: [data binding] let ${step.name}
- Bind: \`${step.name}\` = \`${formatExpr(step.value)}\`
`;
        stepNum++;
        break;

      case 'graph_call':
        text += `
### Step ${stepNum}: [sub-pipeline] ${step.name}(${step.args.map(a => `${a.name}: ${formatExpr(a.value)}`).join(', ')})
- Execute graph \`${step.name}\` with parameters
`;
        stepNum++;
        prev = null;
        break;
    }
  }

  return { text, nextStep: stepNum, lastNode: prev };
}

