import { Program } from '../parser/ast.js';
import { TokenReport } from '../analyzer/estimator.js';

export function generateOrchestration(program: Program, report: TokenReport): string {
  const graph = program.graphs[0];
  if (!graph) return '';

  const edgeMap = new Map<string, boolean>();
  for (const edge of program.edges) {
    if (edge.target.kind === 'direct' && edge.transforms.length > 0) {
      edgeMap.set(`${edge.source}->${edge.target.node}`, true);
    }
  }

  let steps = '';
  for (let i = 0; i < graph.flow.length; i++) {
    const nodeName = graph.flow[i];
    const nodeReport = report.nodes.find(n => n.name === nodeName);
    const lowerName = nodeName.toLowerCase();

    let inputSource = '';
    if (i > 0) {
      const prevNode = graph.flow[i - 1];
      const hasTransform = edgeMap.has(`${prevNode}->${nodeName}`);
      if (hasTransform) {
        inputSource = `\n- Input: \`.graft/session/node_outputs/${prevNode.toLowerCase()}_to_${lowerName}.json\``;
      } else {
        inputSource = `\n- Input: \`.graft/session/node_outputs/${prevNode.toLowerCase()}.json\``;
      }
    }

    steps += `
### Step ${i + 1}: ${nodeName} [sequential]
- Agent: ${lowerName}${inputSource}
- Expected tokens: input ~${nodeReport?.estimatedIn.toLocaleString('en-US') || '?'} / output ~${nodeReport?.estimatedOut.toLocaleString('en-US') || '?'}
- Completion: \`===NODE_COMPLETE:${lowerName}===\`
- Output: \`.graft/session/node_outputs/${lowerName}.json\`
`;
  }

  return `# Graft Orchestration: ${graph.name}

> Auto-generated by Graft Compiler. Edit the .gft source, not this file.

## Budget
Total: ${graph.budget.toLocaleString('en-US')} tokens
Best case: ${report.bestCase.toLocaleString('en-US')} tokens
Worst case: ${report.worstCase.toLocaleString('en-US')} tokens

## Execution Plan
${steps}
## Token Budget Tracking
Check \`.graft/token_log.txt\` after each step.
- 80% consumed: switch remaining agents to compact mode
- 90% consumed: skip non-critical agents

## Failure Recovery
- Agent failure: follow on_failure policy in each agent definition
- Token overrun: switch to compact mode, then skip non-critical steps
- Complete failure: intermediate results preserved in \`.graft/session/\`
`;
}
